001. Web/Mitt_Firdan_NT/Mitt_Firdan_NT/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using Mitt.Commons.ViewModels;
using Mitt.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mitt_Firdan_NT.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillModelAccess _respository;

        public SkillController(ISkillModelAccess repository)
        {
            _respository = repository;
        }

        public async Task<IActionResult> Index(string search)
        {
            var data = await _respository.GetAll();

            List<SkillViewModel> list = new List<SkillViewModel>();

            if (data.IsSuccess)
            {
                if (search != null)
                {
                    foreach (var item in data.Data)
                    {
                        if (item.IsDelete == false && item.SkillName.ToLower().Contains(search.ToLower()))
                        {
                            list.Add(item);
                        }
                    }
                }
                else
                {
                    foreach (var item in data.Data)
                    {
                        if (item.IsDelete == false)
                        {
                            list.Add(item);
                        }
                    }
                }
            }

            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SkillViewModel a, int id)
        {

            await _respository.PostCreate(a);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var data = await _respository.GetById(id);

            SkillViewModel a = new SkillViewModel();
            if (data.IsSuccess && data.Data != null)
            {
                a.SkillId = id;
                a.SkillName = data.Data.SkillName;
                a.CreatedBy = data.Data.CreatedBy;
                a.CreatedOn = data.Data.CreatedOn;
                a.ModifiedBy = data.Data.ModifiedBy;
                a.ModifiedOn = data.Data.ModifiedOn;
                a.IsDelete = data.Data.IsDelete;
                a.DeletedBy = data.Data.DeletedBy;
                a.DeletedOn = data.Data.DeletedOn;


            };
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SkillViewModel a, int id)
        {
            var data2 = await _respository.GetById(id);
            a.CreatedOn = data2.Data.CreatedOn;
            a.CreatedBy = data2.Data.CreatedBy;
            a.ModifiedBy = 1;
            a.ModifiedOn = DateTime.Now;
            await _respository.PostEdit(a);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _respository.GetById(id);

            SkillViewModel a = new SkillViewModel();
            if (response.IsSuccess && response.Data != null)
            {
                a.SkillId = id;
                a.SkillName = response.Data.SkillName;
                a.CreatedBy = response.Data.CreatedBy;
                a.CreatedOn = response.Data.CreatedOn;
                a.ModifiedBy = response.Data.ModifiedBy;
                a.ModifiedOn = response.Data.ModifiedOn;
                a.DeletedBy = response.Data.DeletedBy;
                a.DeletedOn = response.Data.DeletedOn;
                a.IsDelete = response.Data.IsDelete;
            }
            return View(a);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(SkillViewModel a, int id)
        {
            var data2 = await _respository.GetById(id);

            a.SkillName = data2.Data.SkillName;
            a.CreatedOn = data2.Data.CreatedOn;
            a.CreatedBy = data2.Data.CreatedBy;
            a.ModifiedBy = data2.Data.ModifiedBy;
            a.ModifiedOn = data2.Data.ModifiedOn;
            a.DeletedBy = 1;
            a.DeletedOn = DateTime.Now;
            a.IsDelete = true;

            await _respository.PostEdit(a);
            return RedirectToAction("Index");
        }
    }
}

001. Web/Mitt_Firdan_NT/Mitt_Firdan_NT/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Mitt.Commons.ViewModels;
using Mitt.Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mitt_Firdan_NT.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IUserProfile _respository;

        public UserProfileController(IUserProfile repository)
        {
            _respository = repository;
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserProfileViewModel a, int id)
        {

            await _respository.PostCreate(a);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Index(string search)
        {
            var data = await _respository.GetAll();

            List<UserProfileViewModel> list = new List<UserProfileViewModel>();

            if (data.IsSuccess)
            {
                if (search != null)
                {
                    foreach (var item in data.Data)
                    {
                        if (item.IsDelete == false && item.Name.ToLower().Contains(search.ToLower()))
                        {
                            list.Add(item);
                        }
                    }
                }
                else
                {
                    foreach (var item in data.Data)
                    {
                        if (item.IsDelete == false)
                        {
                            list.Add(item);
                        }
                    }
                }
            }
            return View(list);
        }
    }
}

001. Web/Mitt_Firdan_NT/Mitt_Firdan_NT/Views/UserProfile/Create.cshtml
@model Mitt.Commons.ViewModels.UserProfileViewModel

@{ ViewData["Title"] = "Create System Type";
    Layout = "~/Views/Shared/_AceAdminLayout.cshtml";
}

<h1>Create</h1>

<h4>User Profile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Bod" class="control-label"></label>
                <input asp-for="Bod" class="form-control" />
                <span asp-validation-for="Bod" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

001. Web/Mitt_Firdan_NT/Mitt_Firdan_NT/Views/UserProfile/Index.cshtml
@model IEnumerable<Mitt.Commons.ViewModels.UserProfileViewModel>

@{
    ViewData["Title"] = "User Profile";
    Layout = "~/Views/Shared/_AceAdminLayout.cshtml";

}

<h1>User Profile</h1>
<br />
<div class="hidden-sm hidden-xs action-buttons">
    <table class="table table-bordered width-50" align="center">
        <tr>
            <form asp-action="Index">
            <td align="left">
                @using (Html.BeginForm("Index", "Skill", FormMethod.Get))
                {
                    @Html.TextBox("search")
                    <input type="submit" value="Search" align="right" />
                }
            </td>
            </form>
            <td align="right">
                <a class="btn btn-primary btn-sm" asp-action="Create">
                    Register
                </a>
            </td>
        </tr>
    </table>
</div>

<br />
<div class="table-responsive">
    <table class="table table-bordered width-50" align="center">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Username)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Address)</th>
                <th>@Html.DisplayNameFor(model => model.Bod)</th>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                @*<th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                    <th>@Html.DisplayNameFor(model => model.CreatedOn)</th>
                    <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                    <th>@Html.DisplayNameFor(model => model.ModifiedOn)</th>
                    <th>@Html.DisplayNameFor(model => model.DeletedBy)</th>
                    <th>@Html.DisplayNameFor(model => model.DeletedOn)</th>
                    <th>@Html.DisplayNameFor(model => model.IsDelete)</th>*@
                
            </tr>
        </thead>
        <tbody>
            @{ foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Username)</td>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Address)</td>
                        <td>@Html.DisplayFor(modelItem => item.Bod)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                        @*<td>@Html.DisplayFor(modelItem => item.CreatedBy)</td>
                            <td>@Html.DisplayFor(modelItem => item.CreatedOn)</td>
                            <td>@Html.DisplayFor(modelItem => item.ModifiedBy)</td>
                            <td>@Html.DisplayFor(modelItem => item.ModifiedOn)</td>
                            <td>@Html.DisplayFor(modelItem => item.DeletedBy)</td>
                            <td>@Html.DisplayFor(modelItem => item.DeletedOn)</td>
                            <th>@Html.DisplayFor(model => item.IsDelete)</th>*@

                        @*<td>

                            <div class="hidden-sm hidden-xs btn-group">
                                <a class="btn btn-success btn-sm" asp-action="Edit" asp-route-id="@item.IdUserProfile">
                                    Add Now
                                </a>

                                
                            </div>
                        </td>*@
                    </tr>
                } }
        </tbody>
    </table>
</div>